# Generated by Django 3.1 on 2020-08-15 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('close_last', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('open_price', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('symbol', models.CharField(blank=True, max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['symbol'], name='stocks_symb_symbol_fd74b5_idx'),
        ),
        migrations.AddConstraint(
            model_name='symbol',
            constraint=models.UniqueConstraint(fields=('symbol',), name='unique_symbol'),
        ),
        migrations.AddField(
            model_name='dailystock',
            name='symbol',
            field=models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, related_name='daily_stock', to='stocks.symbol'),
        ),
        migrations.AddIndex(
            model_name='dailystock',
            index=models.Index(fields=['symbol', 'date'], name='stocks_dail_symbol_9fbfbf_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailystock',
            constraint=models.UniqueConstraint(fields=('symbol', 'date'), name='unique__symbol_date'),
        ),
    ]
