# Generated by Django 3.1 on 2020-08-16 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('close_last', models.FloatField(blank=True, null=True)),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('open_price', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('symbol', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.CASCADE, related_name='real_time_stock', to='stocks.symbol')),
            ],
        ),
        migrations.AddIndex(
            model_name='realtimestock',
            index=models.Index(fields=['symbol', 'date_time'], name='stocks_real_symbol_31eac6_idx'),
        ),
        migrations.AddConstraint(
            model_name='realtimestock',
            constraint=models.UniqueConstraint(fields=('symbol', 'date_time'), name='unique__symbol_date_time'),
        ),
    ]
